### ISSUE TITLE
Option to disable strict mode in json-validate script?

### ISSUE THREAD

**Issue by yannxou** [j-h-a/ios-build-scripts#2]
Some json files in my projects have control characters in the strings ('\n', etc). Since strict mode in python seems to be enabled by default this causes the script to throw an error.

I couldn't find a way to pass an option to json.tool to disable the strict mode. Do you have any idea?

Thanks!

**Comment by j-h-a** [comment]
I don't use any of these scripts myself any more, so they're quite out of date. I didn't even know anyone else was still using them either :)

Here's what I'd recommend:
1. Take a look at the json.tool code - it's super simple. Here it is: https://github.com/python/cpython/blob/master/Lib/json/tool.py
2. Write your own local script called something like `validatejson.py` loosely based on json.tool - all you really need is the few lines where it tries to load and raises the exception, all the rest is not relevant. This will be a really simple script.
2.1. Create a subclass of `json.JSONDecoder` called `NonStrictJSONDecoder` and override its initialiser to pass in the `strict=False` argument. See example below.
2.2. Use `obj = json.load(sys.stdin, cls=NonStrictJSONDecoder)` to load it.
3. Now from the xcode build rule, instead of `python -m json.tool`, use your `validatejson.py` script.

For step 2.1, I think it would be something like this (untested):
```python
class NonStrictJSONDecoder(json.JSONDecoder):
    def __init__(self, *args, **kwargs):
        json.JSONDecoder.__init__(self, strict=False, *args, **kwargs)
```

I think that should do the trick :)
